use alloc::vec::Vec;

// No resource operation is available yet. Keep every maximum explicit so new
// HAL limits cannot silently inherit a positive default. Nonzero alignment
// sentinels and the lowest ShaderModel are inert while Adapter::open rejects.
pub(super) fn enumeration_only() -> crate::Capabilities {
    crate::Capabilities {
        limits: wgt::Limits {
            max_texture_dimension_1d: 0,
            max_texture_dimension_2d: 0,
            max_texture_dimension_3d: 0,
            max_texture_array_layers: 0,
            max_bind_groups: 0,
            max_bind_groups_plus_vertex_buffers: 0,
            max_bindings_per_bind_group: 0,
            max_dynamic_uniform_buffers_per_pipeline_layout: 0,
            max_dynamic_storage_buffers_per_pipeline_layout: 0,
            max_sampled_textures_per_shader_stage: 0,
            max_samplers_per_shader_stage: 0,
            max_storage_buffers_per_shader_stage: 0,
            max_storage_buffers_in_vertex_stage: 0,
            max_storage_buffers_in_fragment_stage: 0,
            max_storage_textures_per_shader_stage: 0,
            max_storage_textures_in_vertex_stage: 0,
            max_storage_textures_in_fragment_stage: 0,
            max_uniform_buffers_per_shader_stage: 0,
            max_binding_array_elements_per_shader_stage: 0,
            max_binding_array_acceleration_structure_elements_per_shader_stage: 0,
            max_binding_array_sampler_elements_per_shader_stage: 0,
            max_uniform_buffer_binding_size: 0,
            max_storage_buffer_binding_size: 0,
            max_vertex_buffers: 0,
            max_buffer_size: 0,
            max_vertex_attributes: 0,
            max_vertex_buffer_array_stride: 0,
            max_inter_stage_shader_variables: 0,
            min_uniform_buffer_offset_alignment: 1,
            min_storage_buffer_offset_alignment: 1,
            max_color_attachments: 0,
            max_color_attachment_bytes_per_sample: 0,
            max_compute_workgroup_storage_size: 0,
            max_compute_invocations_per_workgroup: 0,
            max_compute_workgroup_size_x: 0,
            max_compute_workgroup_size_y: 0,
            max_compute_workgroup_size_z: 0,
            max_compute_workgroups_per_dimension: 0,
            max_immediate_size: 0,
            max_non_sampler_bindings: 0,
            max_task_workgroup_total_count: 0,
            max_task_workgroups_per_dimension: 0,
            max_mesh_workgroup_total_count: 0,
            max_mesh_workgroups_per_dimension: 0,
            max_task_invocations_per_workgroup: 0,
            max_task_invocations_per_dimension: 0,
            max_mesh_invocations_per_workgroup: 0,
            max_mesh_invocations_per_dimension: 0,
            max_task_payload_size: 0,
            max_mesh_output_vertices: 0,
            max_mesh_output_primitives: 0,
            max_mesh_output_layers: 0,
            max_mesh_multiview_view_count: 0,
            max_blas_primitive_count: 0,
            max_blas_geometry_count: 0,
            max_tlas_instance_count: 0,
            max_acceleration_structures_per_shader_stage: 0,
            max_buffers_and_acceleration_structures_per_shader_stage: 0,
            max_multiview_view_count: 0,
            max_ray_dispatch_count: 0,
            max_ray_recursion_depth: 0,
        },
        alignments: crate::Alignments {
            buffer_copy_offset: wgt::BufferSize::MIN,
            buffer_copy_pitch: wgt::BufferSize::MIN,
            uniform_bounds_check_alignment: wgt::BufferSize::MIN,
            raw_tlas_instance_size: 0,
            ray_tracing_scratch_buffer_alignment: 1,
            ray_tracing_pipeline_group_data_size: 0,
            ray_tracing_pipeline_group_data_alignment: 1,
            ray_tracing_pipeline_data_offset_alignment: 1,
        },
        downlevel: wgt::DownlevelCapabilities {
            flags: wgt::DownlevelFlags::empty(),
            limits: wgt::DownlevelLimits {},
            shader_model: wgt::ShaderModel::Sm2,
        },
        cooperative_matrix_properties: Vec::new(),
    }
}
